services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-net

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:${AUTH_DB_PORT}"
    volumes:
      - data-auth:/var/lib/postgresql
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - auth-db
    networks:
      - app-net

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-net
    command: ["redis-server", "--save", "60", "1"]
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    depends_on:
      - redis
    networks:
      - app-net
    volumes:
     - redis-insight-data:/data

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_AUTH_URL: ${DISCORD_AUTH_URL}
      DISCORD_TOKEN_URL: ${DISCORD_TOKEN_URL}
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_URL: ${REDIS_URL}
      AUTH_DB: ${AUTH_DB}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DB_URL: ${AUTH_DB_URL}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - auth-db
      - redis
    ports:
      - "${AUTH_SERVICE_PORT}:4000"
    networks:
      - app-net


volumes:
  caddy_data:
  caddy_config:
  data-auth:
  redis-data:
  redis-insight-data:

networks:
  app-net:
    driver: bridge