services:
  auth_db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:${AUTH_DB_PORT}"
    volumes:
      - data-auth:/var/lib/postgresql/data
    networks:
      - commi-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - auth_db
    networks:
      - commi-network

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - commi-network
    command: ["redis-server", "--save", "60", "1"]
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    depends_on:
      - redis
    networks:
      - commi-network
    volumes:
     - redis-insight-data:/data

  auth-service:
    build:
      context: ../
      dockerfile: services/auth-service/Dockerfile
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      AUTH_DB: ${AUTH_DB}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
    depends_on:
      - auth_db
      - redis
    ports:
      - "${AUTH_SERVICE_PORT}:4000"
    networks:
      - commi-network

  web-app:
    build:
      context: ../
      dockerfile: apps/web/Dockerfile
    depends_on:
      - auth-service
    ports:
      - "${WEB_APP_PORT}:5173"
    networks:
      - commi-network

volumes:
  data-auth:
  redis-data:
  redis-insight-data:


networks:
  commi-network:
    driver: bridge